val fluidCowTagArray as string[]=[
	"aluminum",
	"alubrass",
	"alumite",
	"ardite",
	"brass",
	"bronze",
	"chrome",
	"cobalt",
	"constantan",
	"copper",
	"electrum",
	"elementium",
	"enderium",
	"enhanced_galgadorian",
	"galgadorian",
	"gold",
	"invar",
	"iridium",
	"iron",
	"knightslime",
	"lead",
	"lumium",
	"manasteel",
	"manyullyn",
	"mana",
	"nickel",
	"platinum",
	"pigiron",
	"reinforced_metal",
	"signalum",
	"silver",
	"steel",
	"terrasteel",
	"tin",
	"titanium",
	"tungsten",
	"tungstensteel",
	"uranium",
	"zinc"
	];
for tag in fluidCowTagArray{
	recipes.addShapeless(<fluidcows:cow_displayer>.withTag({fluid: tag}),
	[<fluidcows:cow_halter>.withTag({t_fluid: tag}).giveBack(<fluidcows:cow_halter>),
	<tconstruct:piggybackpack>]);}
	
recipes.addShaped("cow_halter",<fluidcows:cow_halter>,[
[<hatchery:plastic>,<minecraft:wheat>,<hatchery:plastic>],
[<minecraft:leather>,<ore:stickWood>,<minecraft:leather>],
[null,<ore:stickWood>,null]]);